apps/accounts/urls.py
from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView

from .views import LoginView, LogOutView, SignUpView, index, load_access, \
    EnterpriseAssociationCreateView
from django.contrib.auth import views as auth_views


accounts_patterns = patterns(
    '',
    url(r'^$', index, name='index'),
)

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'plateo.views.home', name='home'),
    url(r'^load_access/(?P<headquar_id>.*)/(?P<module_id>.*)/$',
        load_access, name='load_access'),
    url(r'^add_enterprise/$',
        EnterpriseAssociationCreateView.as_view(), name='add_enterprise'),
    url(r'^$', include(accounts_patterns, namespace='accounts')),

    url(r'^login/$', LoginView.as_view(), name='login'),
    # url(r'^logout/$', auth_views.logout,
    #    {'template_name': 'registration/logged_out.html'}, name='logout'),

    url(r'^logout/$', LogOutView.as_view(), name='logout'),

    url(r'^register/$', SignUpView.as_view(), name='register'),

    url(r'^password_reset/$',
        auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$',
        auth_views.password_reset_done, name='password_reset_done'),
    # Support old style base36 password reset links; remove in Django 1.7
    #url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.password_reset_confirm_uidb36),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,
        name='password_reset_complete'),


    url(r'^password/change/$', auth_views.password_change,
        name='password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done,
        name='password_change_done'),


)

apps/space/urls.py
# _*_ coding: utf-8 _*_
from django.conf.urls import patterns, url

# views
from .views import HeadquarListView, HeadquarUpdateView, HeadquarCreateView, \
    HeadquarUpdateActiveView, HeadquarAssociationUpdateView

from .views import EnterpriseUpdateView, EnterpriseListView, \
    EnterpriseCreateView, EnterpriseDeleteView, EnterpriseUpdateActiveView
from .views import AssociationUpdateView
from .views import SolutionListView, SolutionCreateView,\
    SolutionUpdateView, SolutionDeleteView, SolutionUpdateActiveView

# public
urlpatterns = patterns(
    '',
    url(r'^headquar/update_association/(?P<pk>.*)/$',
        HeadquarAssociationUpdateView.as_view(), name='headquar-update_association'),
    url(r'^headquar/state/(?P<state>[\w\d\-]+)/(?P<pk>.*)/$',
        HeadquarUpdateActiveView.as_view(), name='headquar-state'),
    url(r'^headquar/create/$',
        HeadquarCreateView.as_view(), name='headquar-create'),
    url(r'^headquar/update/(?P<pk>.*)/$',
        HeadquarUpdateView.as_view(), name='headquar-update'),
    url(r'^headquar/index/$',
        HeadquarListView.as_view(), name='headquar-list'),

    # enterprise x asullom
    url(r'^enterprise/state/(?P<state>[\w\d\-]+)/(?P<pk>.*)/$',
        EnterpriseUpdateActiveView.as_view(), name='enterprise-state'),
    url(r'^enterprise/delete/(?P<pk>.*)/$',
        EnterpriseDeleteView.as_view(), name='enterprise-delete'),
    url(r'^enterprise/create/$',
        EnterpriseCreateView.as_view(), name='enterprise-create'),
    url(r'^enterprise/update/(?P<pk>.*)/$',
        EnterpriseUpdateView.as_view(), name='enterprise-update'),
    url(r'^enterprise/index/$',
        EnterpriseListView.as_view(), name='enterprise-list'),
    url(r'^enterprise/edit_current/$',
        EnterpriseUpdateView.as_view(), name='enterprise-edit_current'),


    url(r'^association/edit_current/$',
        AssociationUpdateView.as_view(), name='association-edit_current'),

    # solution x asullom
    url(r'^solution/state/(?P<state>[\w\d\-]+)/(?P<pk>.*)/$',
        SolutionUpdateActiveView.as_view(), name='solution-state'),
    url(r'^solution/delete/(?P<pk>.*)/$',
        SolutionDeleteView.as_view(), name='solution-delete'),
    url(r'^solution/update/(?P<pk>.*)/$',
        SolutionUpdateView.as_view(), name='solution-update'),
    url(r'^solution/create/$',
        SolutionCreateView.as_view(), name='solution-create'),
    url(r'^solution/index/$',
        SolutionListView.as_view(), name='solution-list'),

)

venton/urls.py
# _*_ coding: utf-8 _*_
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

#admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'backengo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),





    url(r'^home/', include('apps.home.urls', namespace='home')),
    url(r'^$', 'apps.home.views.index', name='index'),

    url(r'^space/', include('apps.space.urls', namespace='space')),
    url(r'^sad/', include('apps.sad.urls', namespace='sad')),


    url(r'^mod_backend/',
        include('apps.mod_backend.urls', namespace='mod_backend')),
    url(r'^accounts/', include('apps.accounts.urls')),








    # http://stackoverflow.com/questions/19625102/django-javascript-translation-not-working
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog'),

    # https://docs.djangoproject.com/en/1.6/ref/views/
    # https://docs.djangoproject.com/en/1.6/howto/static-files/
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
    'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
        'show_indexes': settings.DEBUG
        }),
)

apps/space/models.py
# _*_ coding: utf-8 _*_
"""
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     space

Descripcion: Registro de los modelos de la app space
"""
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst
from django.dispatch import receiver
from django.db.models import signals
from unicodedata import normalize
from django.core.exceptions import ValidationError

# models
#from apps.params.models import Locality

# managers
#from .managers import SolutionManager

# others
#from django.utils import timezone
#from django.core.exceptions import NON_FIELD_ERRORS
#from django.template.defaultfilters import slugify

GOVERMENT = 'GOVERMENT'
PRIVATE = 'PRIVATE'
MIXED = 'MIXED'
OTHERS = 'OTHERS'
TYPE_CHOICES = (
    (GOVERMENT, _('Government')),
    (PRIVATE, _('Private')),
    (MIXED, _('Mixed')),
    (OTHERS, _('Others'))
)


def unique_name(value):
    if value == 'angel':
        raise ValidationError(u'%s is not an angel' % value)


class Solution(models.Model):

    """
    Tabla que contiene las soluciones o planes o servicios del sistema
    """
    name = models.CharField(capfirst(_('name')), max_length=50)
    description = models.TextField(_('Description'), null=True, blank=True)
    price = models.FloatField(_('Price'), null=True, blank=True)
    is_active = models.BooleanField(capfirst(_('active')), default=True)

    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)

    test_image = models.ImageField(
        _('Test image'), upload_to='test_images',
        default='test_images/default.png', null=True, blank=True)
    test_date = models.DateTimeField(_('Test date'),
                                     null=True, blank=True)

    class Meta:
        verbose_name = _('Solution')
        verbose_name_plural = _('Solutions')
        permissions = (
            ('solution', 'Can ALL solution'),
        )
        unique_together = ('name',)

    def __str__(self):
        return self.name

    def validate_unique(self, exclude=None):
        if normalize('NFKD', self.name).encode('ascii', 'ignore').lower() in list(
            normalize('NFKD', c['name']).encode('ascii', 'ignore').lower()
            for c in self.__class__.objects.values('name').exclude(pk=self.pk)
        ):
            raise ValidationError({
                'name':
                (_(u'%(model_name)s with this %(field_label)s already exists.') % {
                'model_name': _('Solution'),
                'field_label': capfirst(_('name')),
                },),
            })

        super(Solution, self).validate_unique(exclude=exclude)


class Association(models.Model):

    """
    Tabla que contiene las asociaciones suscritas a un plan
    """

    name = models.CharField(capfirst(_('name')), max_length=50)
    logo = models.ImageField(
        _('Logo'),
        upload_to='associations', default='associations/default.png')
    type_a = models.CharField(
        _('Type'),
        max_length=10, choices=TYPE_CHOICES, default=PRIVATE)
    is_active = models.BooleanField(capfirst(_('active')), default=True)
    is_actived = models.BooleanField(_('Actived'), default=False)

    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)

    solution = models.ForeignKey(
        Solution, verbose_name=_('Solution'), null=True, blank=True)

    class Meta:
        verbose_name = _('Association')
        verbose_name_plural = _('Associations')
        permissions = (
            ('association', 'Can ALL association'),
        )
        unique_together = ('name',)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if normalize('NFKD', u'%s' % self.name).encode('ascii', 'ignore').lower() in list(
                normalize('NFKD', u'%s' % c['name']).encode('ascii', 'ignore').lower() for c in Association.objects.values('name').exclude(pk=self.pk)
        ):
            raise Exception(_(u'%(model_name)s with this %(field_label)s already exists.') % {
                'model_name': _('Association'),
                'field_label': capfirst(_(u'name')),
            })
        super(Association, self).save(*args, **kwargs)


class Enterprise(models.Model):

    """
    Tabla que contiene las empresas suscritas a un plan
    """

    name = models.CharField(capfirst(_('name')), max_length=50)
    #name_sm = models.CharField(capfirst(_('siglas')), max_length=50)
    logo = models.ImageField(
        _('Logo'), upload_to='enterprises', default='enterprises/default.png')
    tax_id = models.CharField(_('Tax id'), max_length=50)
    type_e = models.CharField(
        _('Type'),
        max_length=10, choices=TYPE_CHOICES, default=PRIVATE)
    is_active = models.BooleanField(capfirst(_('active')), default=True)
    is_actived = models.BooleanField(_('Actived'), default=False)

    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)

    solution = models.ForeignKey(
        Solution, verbose_name=_('Solution'), null=True, blank=True)

    class Meta:
        verbose_name = _('Enterprise')
        verbose_name_plural = _('Enterprises')
        permissions = (
            ('enterprise', 'Can ALL enterprise'),
        )
        # no duplicate name, no duplicate tax_id
        unique_together = ('name', 'tax_id',)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if normalize('NFKD', u'%s' % self.name).encode('ascii', 'ignore').lower() in list(
                normalize('NFKD', u'%s' % c['name']).encode('ascii', 'ignore').lower() for c in Enterprise.objects.values('name').exclude(pk=self.pk)
        ):
            raise Exception(_(u'%(model_name)s with this %(field_label)s already exists.') % {
                'model_name': _('Enterprise'),
                'field_label': capfirst(_(u'name')),
            })
        if Enterprise.objects.exclude(pk=self.pk).filter(tax_id=self.tax_id).count() > 0:
            raise Exception(_(u'%(model_name)s with this %(field_label)s already exists.') % {
                'model_name': _('Enterprise'),
                'field_label': capfirst(_(u'Tax id')),
            })
        super(Enterprise, self).save(*args, **kwargs)


class Headquar(models.Model):

    """
    Tabla que contiene las sedes de las empresas, asociadas a una Asociación
    Un Headquar o sede o sucursal, es la unidad principal del sistema
    Los accesos del sistema serán entregados a un Headquarters
    """
    name = models.CharField(capfirst(_('name')), max_length=50)

    phone = models.CharField(_('Phone'), max_length=50, null=True, blank=True)

    address = models.TextField(_('Address'), null=True, blank=True)
    is_main = models.BooleanField(_('Main'), default=False)
    is_active = models.BooleanField(capfirst(_('active')), default=True)
    is_actived = models.BooleanField(_('Actived'), default=False)

    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)

    # locality = models.ForeignKey(Locality, verbose_name=_('Locality'),
    #	null=True, blank=True)
    association = models.ForeignKey(
        Association, verbose_name=_('Association'), null=True, blank=True)
    enterprise = models.ForeignKey(Enterprise, verbose_name=_('Enterprise'))

    class Meta:
        verbose_name = _('Headquar')
        verbose_name_plural = _('Headquars')
        permissions = (
            ('headquar', 'Can ALL headquar(sedes)'),
        )
        # no duplicate name by enterprise
        unique_together = (('name', 'enterprise'),)

    def __str__(self):
        return '%s %s (%s)' % (self.name, self.enterprise, self.association)

    def save(self, *args, **kwargs):
        if normalize('NFKD', u'%s' % self.name).encode('ascii', 'ignore').lower() in list(
                normalize('NFKD', u'%s' % c['name']).encode('ascii', 'ignore').lower() for c in Headquar.objects.values('name').exclude(pk=self.pk).filter(enterprise=self.enterprise)
        ):
            raise Exception(_(u'%(model_name)s with this %(field_label)s already exists.') % {
                'model_name': _('Headquar'),
                'field_label': capfirst(_(u'name')),
            })
        super(Headquar, self).save(*args, **kwargs)

apps/space/templates/space/association_form.html
{% extends "mod_backend/base_mod_backend.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     space

Descripcion: Create/Update solution
-->
{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block breadcrumbs %}
<a href="{% url 'accounts:index' %}">{% trans 'Home' %}</a>

&rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
{{ opts.verbose_name|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}

{% crispy form %}

{% endblock %}

{% block extrajs %}
{{ block.super }}

<script type="text/javascript">
$('#id_logo').fileinput({
	showUpload: false,
	showRemove: false,
	initialCaption: '{{ form.logo.value }}',
	initialPreview: ['<img src="{{ MEDIA_URL }}{{ form.logo.value }}">',],
	browseClass: 'btn btn-warning',
	browseLabel: '<span class="hidden-xs">{% trans "Pick image" %}</span>',
	browseIcon: '<i class="btn-icon-only glyphicon glyphicon-picture"></i>',
});

</script>
{% endblock extrajs %}

apps/space/templates/space/enterprise_form.html
{% extends "mod_backend/base_mod_backend.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     space

Descripcion: Create/Update solution
-->
{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block breadcrumbs %}
<a href="{% url 'accounts:index' %}">{% trans 'Home' %}</a>
&rsaquo;
<a href="/space/enterprise/index/">{{ opts.verbose_name_plural|capfirst }}</a>
&rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
{{ opts.verbose_name|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}

{% crispy form %}

{% endblock %}

{% block extrajs %}
{{ block.super }}

<script type="text/javascript">
$('#id_logo').fileinput({
	showUpload: false,
	showRemove: false,
	initialCaption: '{{ form.logo.value }}',
	initialPreview: ['<img src="{{ MEDIA_URL }}{{ form.logo.value }}">',],
	browseClass: 'btn btn-warning',
	browseLabel: '<span class="hidden-xs">{% trans "Pick image" %}</span>',
	browseIcon: '<i class="btn-icon-only glyphicon glyphicon-picture"></i>',
});

</script>
{% endblock extrajs %}

apps/space/templates/space/enterprise_list.html
{% extends "mod_backend/base_mod_backend.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     space

Descripcion: Lista enterprises
-->
{% load i18n app_security %}
{% load l10n humanize %}

{% block breadcrumbs %}
<a href="{% url 'accounts:index' %}">{% trans 'Home' %}</a>
&rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
{{ opts.verbose_name_plural|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}
<script type="text/javascript">
$(function() {
    $('table').kgrid({
        form_data : ['{{f}}', '{{q}}'],
        form_to   : '/space/enterprise/index/?f={{f}}&q={{q}}',
        order_attr: 'class=""',
        order_to  : '/space/enterprise/index/?f={{f}}&q={{q}}',
    });
});
</script>

<div class="btn-toolbar btn-toolbar-top">
    <div class="row">
        <div class="btn-actions">
            <a href="/space/enterprise/create/" class="btn btn-primary text-bold" title="{% trans 'Add' %} {% trans 'Enterprise' %}"><i class="fa fa-plus"></i> <span class="hidden-xs"> {% trans 'Add'  %}</span></a> 
        </div>            
    </div>
</div>
<div class="container-overflow">
    <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
        <thead>
            <tr>
                <th>#</th>
                <th class="col-hidden" data-search="name" data-order="name">{% trans 'name'|capfirst %}</th>
                <th class="col-hidden" data-search="tax_id" data-order="tax_id">{% trans 'Tax id' %}</th>
                <th class="col-hidden" data-order="type_e">{% trans 'Type' %}</th>
                <th class="col-hidden">{% trans 'Sedes/de' %}</th>
                <th class="col-hidden">{% trans 'active'|capfirst %}</th>
                <th class="btn-actions col-blocked text-center">{% trans 'Action' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for d in object_list %}       
            <tr class="{{ d.is_active|yesno:',danger' }}">
                <td>{% if is_paginated %}
                    {{ page_obj.start_index|add:forloop.counter0 }}
                    {% else %}
                    {{ forloop.counter }}
                    {% endif %}
                </td>
                <td>{{ d.name }} </td>
                <td>{{ d.tax_id }} </td>
                <td>{{ d.get_type_e_display }} </td>
                <td>{{ d.num_sedes }}/{{ d.headquar_set.all.count }}</td>
                <td>
                    <span class="label label-{{ d.is_active|yesno:'primary,success' }}">
                        {% if d.is_active %}{% trans 'Yes'|upper %} {% else %} {% trans 'No'|upper %} {% endif %}
                    </span>
                </td>
                <td class="text-center">
                    <a href="/space/enterprise/update/{{d.pk|key:'enterprise_upd'}}/" class="btn btn-info btn-sm text-bold" title="{% trans 'Change' %} {% trans 'Enterprise' %}" rel="tooltip"><i class="btn-icon-only fa fa-edit"></i></a>

                    {% if d.is_active %}

                    <a href="/space/enterprise/state/ina/{{d.pk|key:'enterprise_ina'}}/" class="btn btn-success btn-sm text-bold" title="{% trans 'inactivate'|capfirst %} {% trans 'Enterprise' %}" rel="tooltip"><i class="btn-icon-only fa fa-flag"></i></a>

                    {% else %}

                    <a href="/space/enterprise/state/rea/{{d.pk|key:'enterprise_rea'}}/" class="btn btn-info btn-sm text-bold" title="{% trans 'reactivate'|capfirst %} {% trans 'Enterprise' %}" rel="tooltip"><i class="btn-icon-only fa fa-flag"></i></a>

                    {% endif %}

                    
                    <a href="/space/enterprise/delete/{{d.pk|key:'enterprise_del'}}/" class="btn btn-danger btn-sm js-confirm text-bold" msg-title="{% trans 'Delete' %} {% trans 'Enterprise' %}?." msg="{% trans 'Are you sure?' %}<br/>{% trans 'Remember that this operation can not be reversed.' %}" title="{% trans 'Delete' %} {% trans 'Enterprise' %}" rel="tooltip"><i class="btn-icon-only fa fa-trash-o"></i></a>

                    

                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>
<div  class="row" >
    {% if is_paginated %}
    {% load paginator %}
    {% paginator %}
    {% else %}
    <div class="col-md-12" >
        <ul class="breadcrumbpag" >
            {{ object_list.count }} {% ifequal object_list.count 1 %}{{ opts.verbose_name|capfirst }}{% else %}{{ opts.verbose_name_plural|capfirst }}{% endifequal %}
        </ul>
    </div>
    {% endif %}
</div>

{% endblock content %}

apps/space/templates/space/headquar_form.html
{% extends "mod_backend/base_mod_backend.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     space

Descripcion: Create/Update solution
-->
{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block breadcrumbs %}
<a href="{% url 'accounts:index' %}">{% trans 'Home' %}</a>
&rsaquo;
<a href="/space/headquar/index/">{{ opts.verbose_name_plural|capfirst }}</a>
&rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
{{ opts.verbose_name|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}

{% crispy form %}

{% endblock %}

{% block extrajs %}
{{ block.super }}

<script type="text/javascript">
$('#id_logo').fileinput({
	showUpload: false,
	showRemove: false,
	initialCaption: '{{ form.logo.value }}',
	initialPreview: ['<img src="{{ MEDIA_URL }}{{ form.logo.value }}">',],
	browseClass: 'btn btn-warning',
	browseLabel: '<span class="hidden-xs">{% trans "Pick image" %}</span>',
	browseIcon: '<i class="btn-icon-only glyphicon glyphicon-picture"></i>',
});

</script>
{% endblock extrajs %}

apps/space/templates/space/headquarassociation_form.html
{% extends "mod_backend/base_mod_backend.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     space

Descripcion: Create/Update solution
-->
{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block breadcrumbs %}
<a href="{% url 'accounts:index' %}">{% trans 'Home' %}</a>
&rsaquo;
<a href="/space/headquar/index/">{{ opts.verbose_name_plural|capfirst }}</a>
&rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
{{ opts.verbose_name|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}

{% crispy form %}

{% endblock %}

{% block extrajs %}
{{ block.super }}

<script type="text/javascript">
var json_data = {{ association_name_list|safe }};
$(function() {
	$('#id_association_name').typeahead({
		source: json_data, items:5
	});
});

</script>
{% endblock extrajs %}

apps/space/templates/space/solution_form.html
{% extends "mod_backend/base_mod_backend.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     space

Descripcion: Create/Update solution
-->
{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block breadcrumbs %}
<a href="{% url 'accounts:index' %}">{% trans 'Home' %}</a>
&rsaquo;
<a href="/space/solution/index/">{{ opts.verbose_name_plural|capfirst }}</a>
&rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
{{ opts.verbose_name|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}
{{ now }} | {{ 2.67 |unlocalize}}

<ul>{{ nested|unordered_list }}</ul>
{% crispy form %}

{% endblock %}

{% block extrajs %}
{{ block.super }}

<script type="text/javascript">
$('#id_test_image').fileinput({
	showUpload: false,
	showRemove: false,
	initialCaption: '{{ form.test_image.value }}',
	initialPreview: ['<img src="{{ MEDIA_URL }}{{ form.test_image.value }}">',],
	browseClass: 'btn btn-warning',
	browseLabel: '<span class="hidden-xs">{% trans "Pick image" %}</span>',
	browseIcon: '<i class="btn-icon-only glyphicon glyphicon-picture"></i>',
});

$('#id_test_date').datetimepicker({
	format: 'YYYY-MM-DD',
		//format: 'YYYY-MM-DD hh:mm:ss', //pata datatimes
		language: '{{ LANGUAGE_CODE }}',
		pickTime: false,
		//showMeridian: true,
		autoclose: true,
		todayHighlight: true,
	});

</script>
{% endblock extrajs %}