apps/accounts/urls.py
from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView

from .views import LoginView, LogOutView, SignUpView, index, load_access, \
    EnterpriseAssociationCreateView
from django.contrib.auth import views as auth_views


accounts_patterns = patterns(
    '',
    url(r'^$', index, name='index'),
)

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'plateo.views.home', name='home'),
    url(r'^load_access/(?P<headquar_id>.*)/(?P<module_id>.*)/$',
        load_access, name='load_access'),
    url(r'^add_enterprise/$',
        EnterpriseAssociationCreateView.as_view(), name='add_enterprise'),
    url(r'^$', include(accounts_patterns, namespace='accounts')),

    url(r'^login/$', LoginView.as_view(), name='login'),
    # url(r'^logout/$', auth_views.logout,
    #    {'template_name': 'registration/logged_out.html'}, name='logout'),

    url(r'^logout/$', LogOutView.as_view(), name='logout'),

    url(r'^register/$', SignUpView.as_view(), name='register'),

    url(r'^password_reset/$',
        auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$',
        auth_views.password_reset_done, name='password_reset_done'),
    # Support old style base36 password reset links; remove in Django 1.7
    #url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.password_reset_confirm_uidb36),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,
        name='password_reset_complete'),


    url(r'^password/change/$', auth_views.password_change,
        name='password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done,
        name='password_change_done'),


)

apps/sad/urls.py
# _*_ coding: utf-8 _*_
from django.conf.urls import patterns, url  # , include

# views
from .views import UserListView, UserCreateView, UserUpdateView, \
    UserDeleteView, UserActiveUpdateView, PersonListView

from .views import MenuListView, MenuCreateView, MenuUpdateView, \
    MenuDeleteView, MenuUpdateActiveView, UserDetailView

from .views import ModuleListView, ModuleCreateView, \
    ModuleUpdateView, ModuleDeleteView, ModuleUpdateActiveView, \
    ModuleSolutionsUpdateView

from .views import GroupListView, GroupCreateView, GroupUpdateView,\
    GroupDeleteView, GroupPermissionsUpdateView

from .views import PermissionListView, PermissionCreateView, \
    PermissionUpdateView, PermissionDeleteView

# public
urlpatterns = patterns(
    '',
    # user x asullom
     url(r'^user/person_add/(?P<pk>.*)/$',
        UserCreateView.as_view(), name='user-person_add'),
    url(r'^user/person_search/$',
        PersonListView.as_view(), name='user-person_search'),
    url(r'^user/detail/(?P<pk>.*)/$',
        UserDetailView.as_view(), name='user-detail'),
    url(r'^user/state/(?P<state>[\w\d\-]+)/(?P<pk>.*)/$',
        UserActiveUpdateView.as_view(), name='user-state'),
    url(r'^user/delete/(?P<pk>.*)/$',
        UserDeleteView.as_view(), name='user-delete'),
    url(r'^user/update/(?P<pk>.*)/$',
        UserUpdateView.as_view(), name='user-update'),
    url(r'^user/create/$',
        UserCreateView.as_view(), name='user-create'),
    url(r'^user/index/$',
        UserListView.as_view(), name='user-list'),

    # menu x asullom
    url(r'^menu/state/(?P<state>[\w\d\-]+)/(?P<pk>.*)/$',
        MenuUpdateActiveView.as_view(), name='menu-state'),
    url(r'^menu/delete/(?P<pk>.*)/$',
        MenuDeleteView.as_view(), name='menu-delete'),
    url(r'^menu/update/(?P<pk>.*)/$',
        MenuUpdateView.as_view(), name='menu-update'),
    url(r'^menu/create/$',
        MenuCreateView.as_view(), name='menu-create'),
    url(r'^menu/index/$',
        MenuListView.as_view(), name='menu-list'),

    # module x asullom
    url(r'^modulesolutions/update/$',  # modulesolutions es el controller
        ModuleSolutionsUpdateView.as_view(), name='modulesolutions-update'),
    url(r'^module/state/(?P<state>[\w\d\-]+)/(?P<pk>.*)/$',
        ModuleUpdateActiveView.as_view(), name='module-state'),
    url(r'^module/delete/(?P<pk>.*)/$',
        ModuleDeleteView.as_view(), name='module-delete'),
    url(r'^module/update/(?P<pk>.*)/$',
        ModuleUpdateView.as_view(), name='module-update'),
    url(r'^module/create/$',
        ModuleCreateView.as_view(), name='module-create'),
    url(r'^module/index/$',
        ModuleListView.as_view(), name='module-list'),

    # group x asullom
    url(r'^grouppermissions/update/$',  # grouppermissions es el controller
        GroupPermissionsUpdateView.as_view(), name='grouppermissions-update'),
    url(r'^group/delete/(?P<pk>.*)/$',
        GroupDeleteView.as_view(), name='group-delete'),
    url(r'^group/update/(?P<pk>.*)/$',
        GroupUpdateView.as_view(), name='group-update'),
    url(r'^group/create/$',
        GroupCreateView.as_view(), name='group-create'),
    url(r'^group/index/$',
        GroupListView.as_view(), name='group-list'),

    # permission x asullom
    url(r'^permission/delete/(?P<pk>.*)/$',
        PermissionDeleteView.as_view(), name='permission-delete'),  # x pony
    url(r'^permission/update/(?P<pk>.*)/$',
        PermissionUpdateView.as_view(), name='permission-update'),
    url(r'^permission/create/$',
        PermissionCreateView.as_view(), name='permission-create'),
    url(r'^permission/index/$',
        PermissionListView.as_view(), name='permission-list'),
    #url(r'^permission/', include(permission_patterns)),
)


permission_patterns = patterns(
    '',
    url(r'^index/$',
        PermissionListView.as_view(), name='permission-list'),

    url(r'^create/$',
        PermissionCreateView.as_view(), name='permission-create'),

    url(r'^update/(?P<pk>.*)/$',
        PermissionUpdateView.as_view(), name='permission-update'),

    url(r'^delete/(?P<pk>.*)/$',
        PermissionDeleteView.as_view(), name='permission-delete'),

)

venton/urls.py
# _*_ coding: utf-8 _*_
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

#admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'backengo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),





    url(r'^home/', include('apps.home.urls', namespace='home')),
    url(r'^$', 'apps.home.views.index', name='index'),

    url(r'^space/', include('apps.space.urls', namespace='space')),
    url(r'^sad/', include('apps.sad.urls', namespace='sad')),


    url(r'^mod_backend/',
        include('apps.mod_backend.urls', namespace='mod_backend')),
    url(r'^accounts/', include('apps.accounts.urls')),








    # http://stackoverflow.com/questions/19625102/django-javascript-translation-not-working
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog'),

    # https://docs.djangoproject.com/en/1.6/ref/views/
    # https://docs.djangoproject.com/en/1.6/howto/static-files/
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
    'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
        'show_indexes': settings.DEBUG
        }),
)

apps/sad/models.py
# _*_ coding: utf-8 _*_
"""
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     auth
@Descripcion Definición de los modelos
"""
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst, get_text_list
from django.dispatch import receiver
from django.db.models import signals
from unicodedata import normalize
from django.core.exceptions import ValidationError
from django.core.exceptions import NON_FIELD_ERRORS

# models
from django.contrib.auth.models import AbstractUser
from apps.params.models import Person
from django.contrib.auth.models import Group, Permission
from apps.space.models import Solution, Association, Enterprise, Headquar

# managers
from .managers import UserManager

# others


# TODO Is done por ahora



ON = 'ON'
OFF = 'OFF'
USER_STATUS_CHOICES = (
    (ON, _('Activate')),
    (OFF, _('Deactivate')),

)


class User(AbstractUser):

    """
    Tabla para usuarios
    """

    class Meta:
        # swappable = 'AUTH_USER_MODEL' #ver django-angular-seed
        verbose_name = capfirst(_('user'))
        verbose_name_plural = capfirst(_('users'))
        permissions = (
            ('user', 'Can ALL user'),
        )
        db_table = 'auth_user'

    # comentar desde aqui
    last_headquar_id = models.CharField(max_length=50, null=True, blank=True)
    last_module_id = models.CharField(max_length=50, null=True, blank=True)
    person = models.OneToOneField(
        Person, verbose_name=_('Person'), null=True, blank=True,
        # unique=True OneToOneField ya es unico
        # related_name='user'
    )
    # hgroups = models.ManyToManyField(Group, verbose_name=_(u'groups'),
    #                                   through='UserHeadquar',
    # related_name='users_as_group', null=True, blank=True)

    objects = UserManager()  # override the default manager

    def __str__(self):
        return self.username

    '''
    def validate_unique(self, exclude=None):

        raise ValidationError(
            {
                NON_FIELD_ERRORS:
                ('Person with same ... already exists.',)
            }
        )
        super(User, self).validate_unique(exclude=exclude)
    '''
    '''
    def clean(self):
        #raise ValidationError('foo must not be empty')
        raise ValidationError(
            {
                'identity_num':
                ('Person with same ... already exists.',)
            }
        )
    '''

    '''
    def save(self, *args, **kwargs):
        # TODO Mandar con Exception no con ValidationError
        if Person.objects.exclude(id=self.person.id).filter(identity_type=self.person.identity_type, identity_num=self.person.identity_num).count() > 0:
            raise ValidationError({
                'identity_num':
                (_(u'%(model_name)s with this %(field_label)s already exists.') % {
                    'model_name': _('Person'),
                    'field_label': get_text_list( (capfirst(_('number')), capfirst(_('Type')) ),_('and') ),
                },),
            })
        return super(User, self).save(*args, **kwargs)
    '''
    '''
    def validate_unique(self, exclude=None):
        # if self.person:
        if Person.objects.exclude(id=self.person.id).filter(identity_type=self.person.identity_type, identity_num=self.person.identity_num).count() > 0:
            raise ValidationError({
                'identity_num':
                (_(u'%(model_name)s with this %(field_label)s already exists.') % {
                    'model_name': _('Person'),
                    'field_label': get_text_list( (capfirst(_('number')), capfirst(_('Type')) ),_('and') ),
                },),
            })

        return super(User, self).validate_unique(exclude=exclude)
    '''
    '''
    def save(self, *args, **kwargs):
        pk = self.pk
        if self.person:
            self.first_name = self.person.first_name
            self.last_name = self.person.last_name

        super(User, self).save(*args, **kwargs)
        if not pk: # solo despues de crear un nuevo usuario
            UserStatus.objects.create(description='alta', user=self)
    '''


def user_pre_save(sender, instance, raw, **kwargs):
    if instance.person:
        instance.first_name = instance.person.first_name
        instance.last_name = instance.person.last_name


@receiver(signals.post_save, sender=User)
def user_post_save(sender, instance, created, raw, **kwargs):
    if created:  # solo despues de crear un nuevo usuario
        UserStatus.objects.create(description='Alta', user=instance)

signals.pre_save.connect(user_pre_save, sender=User)
#signals.post_save.connect(user_post_save, sender=User)



class UserStatus(models.Model):

    """
    Tabla para el historial de los estados de los usuarios
    """

    status = models.CharField(
        _('Status'), max_length=50, choices=USER_STATUS_CHOICES, default=ON
    )
    description = models.TextField(_('Description'), null=True, blank=True)
    # related_name=userstatus_set
    user = models.ForeignKey(User, verbose_name=capfirst(_('user')))
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)

    class Meta:
        verbose_name = _('User status')
        verbose_name_plural = _('User statuses')
        db_table = 'sad_user_status'

    def __str__(self):
        return '%s %s' % (self.user.username, self.status)


INPUT = "INPUT"
OUTPUT = "OUTPUT"

ACCESS_TYPE_CHOICES = (
    (INPUT, "Input"),
    (OUTPUT, "Output"),

)


class Access(models.Model):

    """
    Tabla que registra los accesos de los usuarios al sistema
    """

    access_type = models.CharField(
        _('Access type'),
        max_length=50, choices=ACCESS_TYPE_CHOICES, default=INPUT)
    ip = models.CharField(_('IP'), max_length=50, null=True, blank=True)
    session_key = models.TextField(_('Session key'), null=True, blank=True)

    user = models.ForeignKey(User, verbose_name=capfirst(_('user')))
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)

    class Meta:
        verbose_name = _('Access')
        verbose_name_plural = _('Accesses')
        permissions = (
            ("access", "Can ALL access"),
        )

    def __str__(self):
        return "%s %s" % (self.user.username, self.access_type)

PRO = 'PRO'
WEB = 'WEB'
VENTAS = 'VENTAS'
BACKEND = 'BACKEND'
MODULE_CHOICES = (
    (PRO, 'Profesional'),
    (WEB, 'Web informativa'),
    (VENTAS, 'Ventas'),
    (BACKEND, 'Backend Manager'),
)


class Module(models.Model):

    """
    Modulos del sistema
    """

    module = models.CharField(
        _('Module'), max_length=50, choices=MODULE_CHOICES, default=BACKEND)
    name = models.CharField(capfirst(_('name')), max_length=50)
    is_active = models.BooleanField(capfirst(_('active')), default=True)
    icon = models.CharField(_('Icon'), max_length=50, null=True, blank=True)
    description = models.TextField(_('Description'), null=True, blank=True)

    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)

    solutions = models.ManyToManyField(
        Solution, verbose_name=_('Solutions'), null=True, blank=True)  # , through='ModuleSolution'

    groups = models.ManyToManyField(
        Group, related_name='module_set', verbose_name=capfirst(_('groups')),
        null=True, blank=True)  # , through='ModuleGroup'
    # related_name cambia module_set x initial_groups_module_set
    initial_groups = models.ManyToManyField(
        Group, related_name='initial_groups_module_set',
        verbose_name=_('Initial groups'), null=True, blank=True)  # , through='ModuleInitialGroup'

    class Meta:

        ordering = ['-id', ]
        verbose_name = _('Module')
        verbose_name_plural = _('Modules')
        permissions = (
            ('module', 'Can ALL module'),
        )
        unique_together = ('module', 'name',)

    def __str__(self):
        return '%s (%s)' % (self.name, dict((x, y)
                                            for x, y in MODULE_CHOICES)[self.module])

    def validate_unique(self, exclude=None):
        if normalize('NFKD', self.name).encode('ascii', 'ignore').lower() in list(
            normalize('NFKD', c['name']).encode('ascii', 'ignore').lower()
            for c in self.__class__.objects.values('name').exclude(pk=self.pk).filter(module=self.module)
        ):
            raise ValidationError({
                'name':
                (_(u'%(model_name)s with this %(field_label)s already exists.') % {
                'model_name': '%s "%s"' % (capfirst(_('Module')) + '', dict(MODULE_CHOICES).get(self.module)),
                'field_label': capfirst(_('name')),
                }, ),
            })
        super(Module, self).validate_unique(exclude=exclude)





class Menu(models.Model):

    """
    Menus del sistema
    """

    module = models.CharField(
        _('Module'), max_length=50, choices=MODULE_CHOICES, default=BACKEND)
    title = models.CharField(capfirst(_('title')), max_length=50)
    url = models.CharField(max_length=150, default='#')
    pos = models.IntegerField(_('Position'), max_length=50, default=1)
    icon = models.CharField(
        _('Icon'), max_length=50, null=True, blank=True, default='')
    is_active = models.BooleanField(capfirst(_('active')), default=True)
    description = models.TextField(_('Description'), null=True, blank=True)

    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)

    permission = models.ForeignKey(
        Permission, verbose_name=_('permission'), null=True, blank=True)
    # related_name='parent',
    parent = models.ForeignKey(
        'self', verbose_name=_('Parent'), null=True, blank=True)

    class Meta:
        verbose_name = _('Menu')

apps/sad/templates/sad/group_form.html
{% extends "mod_backend/base_mod_backend.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     sad

Descripcion: Create/Update group
-->
{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block breadcrumbs %}
<a href="{% url 'accounts:index' %}">{% trans 'Home' %}</a>
&rsaquo;
<a href="/sad/group/index/">{{opts.verbose_name_plural|capfirst}}</a>
&rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
{{ opts.verbose_name|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}

{% crispy form %}

{% endblock %}

{% block extrajs %}
{{ block.super }}

<script type="text/javascript">

</script>
{% endblock extrajs %}

apps/sad/templates/sad/menu_form.html
{% extends "mod_backend/base_mod_backend.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     sad

Descripcion: Create/Update group
-->
{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block breadcrumbs %}
<a href="{% url 'accounts:index' %}">{% trans 'Home' %}</a>
&rsaquo;
<a href="/sad/menu/index/">{{opts.verbose_name_plural|capfirst}}</a>
&rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
{{ opts.verbose_name|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}

{% crispy form %}

{% endblock %}

{% block extrajs %}
{{ block.super }}

<script type="text/javascript">
$(function(){
	$("#id_permission").on('change',function(){
		var recurso = $('option:selected',this).text();
		$("#id_url").val(recurso.replace("/\./g",'/'));
		$("#id_url").val(recurso.replace('/*','/'));

		$("#id_url").val(recurso.replace('_','/')+"/");
	});
});
</script>
{% endblock extrajs %}

apps/sad/templates/sad/menu_list.html
{% extends "mod_backend/base_mod_backend.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     sad

Descripcion: Lista menu
-->
{% load i18n app_security %}
{% load l10n humanize %}

{% block breadcrumbs %}
<a href="{% url 'accounts:index' %}">{% trans 'Home' %}</a>
&rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
{{ opts.verbose_name_plural|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}
<script type="text/javascript">
$(function() {
    $('table').kgrid({
        form_data : ['{{f}}', '{{q}}'],
        form_to   : '/sad/menu/index/?f={{f}}&q={{q}}',
        order_attr: 'class=""',
        order_to  : '/sad/menu/index/?f={{f}}&q={{q}}',
    });
});
</script>

<div class="btn-toolbar btn-toolbar-top">
    <div class="row">
        <div class="btn-actions">
            <a href="/sad/menu/create/" class="btn btn-primary text-bold" title="{% trans 'Add' %} {% trans 'Menu' %}"><i class="fa fa-plus"></i> <span class="hidden-xs"> {% trans 'Add'  %}</span></a> 
        </div>            
    </div>
</div>
<div class="container-overflow">
    <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
        <thead>
            <tr>
                <th>#</th>
                <th class="col-hidden" data-search="module" data-order="module">{% trans 'Module' %}</th>
                <th class="col-hidden" data-search="pos" data-order="pos">{% trans 'Position' %}</th>
                <th class="col-hidden" data-search="parent" data-order="parent">{% trans 'Parent' %}</th>
                <th class="col-hidden" data-search="title" data-order="title">{% trans 'title'|capfirst %}</th>
                <th class="col-hidden" data-search="permission" data-order="permission">{% trans 'permission'|capfirst %}</th>
                <th class="col-hidden" data-search="url" data-order="url">{% trans 'URL' %}</th>
                <th class="col-hidden" data-search="icon" data-order="icon">{% trans 'Icon' %}</th>
                <th class="col-hidden" data-search="active" data-order="active">{% trans 'active'|capfirst %}</th>

                <th class="btn-actions col-blocked text-center">{% trans 'Action' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for d in object_list %}       
            <tr class="{{ d.is_active|yesno:',danger' }}">
                <td>{% if is_paginated %}
                    {{ page_obj.start_index|add:forloop.counter0 }}
                    {% else %}
                    {{ forloop.counter }}
                    {% endif %}
                </td>
                <td><span class="label label-{{ d.is_active|yesno:'primary,success' }}">{{ d.get_module_display }}</span></td>
                <td>{{ d.pos }}</td>
                <td>{{ d.parent.title }}</td>
                <td>{{ d.title  }} </td>
                <td>{{ d.permission.content_type.app_label }}{{ d.permission_id|yesno:'.,'}}{{ d.permission.codename }}</td>
                 <td>{{ d.url }}</td>
                <td>{{ d.icon }}</td>
                <td>
                    <span class="label label-{{ d.is_active|yesno:'primary,success' }}">
                        {% if d.is_active %}{% trans 'Yes'|upper %} {% else %} {% trans 'No'|upper %} {% endif %}
                    </span>
                </td>


                <td class="text-center">
                    <a href="/sad/menu/update/{{d.pk|key:'menu_upd'}}/" class="btn btn-info btn-sm text-bold" title="{% trans 'Change' %} {% trans 'Menu' %}" rel="tooltip"><i class="btn-icon-only fa fa-edit"></i></a>

                    {% if d.is_active %}

                    <a href="/sad/menu/state/ina/{{d.pk|key:'menu_ina'}}/" class="btn btn-success btn-sm text-bold" title="{% trans 'inactivate'|capfirst %} {% trans 'Menu' %}" rel="tooltip"><i class="btn-icon-only fa fa-flag"></i></a>

                    {% else %}

                    <a href="/sad/menu/state/rea/{{d.pk|key:'menu_rea'}}/" class="btn btn-info btn-sm text-bold" title="{% trans 'reactivate'|capfirst %} {% trans 'Menu' %}" rel="tooltip"><i class="btn-icon-only fa fa-flag"></i></a>

                    {% endif %}
                    
                    <a href="/sad/menu/delete/{{d.pk|key:'menu_del'}}/" class="btn btn-danger btn-sm js-confirm text-bold" msg-title="{% trans 'Delete' %} {% trans 'Menu' %}?." msg="{% trans 'Are you sure?' %}<br/>{% trans 'Remember that this operation can not be reversed.' %}" title="{% trans 'Delete' %} {% trans 'Menu' %}" rel="tooltip"><i class="btn-icon-only fa fa-trash-o"></i></a>

                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>
<div  class="row" >
    {% if is_paginated %}
    {% load paginator %}
    {% paginator %}
    {% else %}
    <div class="col-md-12" >
        <ul class="breadcrumbpag" >
            {{ object_list.count }} {% ifequal object_list.count 1 %}{{ opts.verbose_name|capfirst }}{% else %}{{ opts.verbose_name_plural|capfirst }}{% endifequal %}
        </ul>
    </div>
    {% endif %}
</div>

{% endblock content %}

apps/sad/templates/sad/module_form.html
{% extends "mod_backend/base_mod_backend.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     sad

Descripcion: Create/Update module
-->
{% load i18n crispy_forms_tags staticfiles %}
{% load l10n %}

{% block breadcrumbs %}
<a href="{% url 'accounts:index' %}">{% trans 'Home' %}</a>
&rsaquo;
<a href="/sad/module/index/">{{opts.verbose_name_plural|capfirst}}</a>
&rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
{{ opts.verbose_name|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}

{% crispy form %}

{% endblock %}

{% block extrastyle %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'custom/css/admin.css' %}">
{% endblock extrastyle %}
{% block extrajs %}
{{ block.super }}
<script src="{% static 'admin/js/core.js' %}"></script>
<script src="{% static 'admin/js/jquery.js' %}"></script> 
<script src="{% static 'admin/js/jquery.init.js' %}"></script>

<script src="{% static 'admin/js/SelectBox.js' %}"></script>
<script src="{% static 'admin/js/SelectFilter2.js' %}"></script>


<script type="text/javascript">
$(function(){
            $('#id_module').on('change',function(){
                var item = $('option:selected',this).text();
                $('#id_name').val(item);
            });

            jQuery.each($('#id_groups'), function () {
                // "Locations" can be any label you want
                SelectFilter.init('id_groups', "{% trans 'groups'|capfirst %}", false, '/static/admin/');
            });

            jQuery.each($('#id_initial_groups'), function () {
                // "Locations" can be any label you want
                SelectFilter.init('id_initial_groups', "{% trans 'groups'|capfirst %} ini.", true, '/static/admin/');
            });

        });
</script>
{% endblock extrajs %}

apps/sad/templates/sad/permission_form.html
{% extends "mod_backend/base_mod_backend.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     sad

Descripcion: Create/Update permission
-->
{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block breadcrumbs %}
<a href="{% url 'accounts:index' %}">{% trans 'Home' %}</a>
&rsaquo;
<a href="/sad/permission/index/">{{opts.verbose_name_plural|capfirst}}</a>
&rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
{{ opts.verbose_name|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}

{% crispy form %}

{% endblock %}

{% block extrajs %}
{{ block.super }}

<script type="text/javascript">

</script>
{% endblock extrajs %}